### ISSUE TITLE
Upgrade mongodb-sync-4 to 4.3.2

### ISSUE THREAD

**Issue by tleveque** [mongock/mongock-driver-mongodb#385]
Hello,
Is it possible to move to last version of mongodb sync driver to benefit last mongo features ?
Thanks

**Comment by dieppa** [comment]
Hello @tleveque ,

these dependencies are quite up to date in the version 5 we have released recently. 
This is the cofinguration is currently(however, in next releases we will update them to the latest ones)
```xml
    <spring-data-3.version>3.2.5</spring-data-3.version>
    <spring-data-2.version>2.2.13.RELEASE</spring-data-2.version>
    <mongodb-sync-4.version>4.3.2</mongodb-sync-4.version>
    <mongodb-driver-3.version>3.12.10</mongodb-driver-3.version>
```

Although, as said, we have released the version 5.0.8.RC, we haven't still make it public as we are still working on the documentation, our expectation is next week or week after.

If you want to upgrade to the version 5, please follow this [temporal guide](https://github.com/mongock/mongock-driver-mongodb/blob/develop/QUICK_UPGRADE_VERSION_5.md). We'll help you in anything you need to have it working.

**Comment by tleveque** [comment]
Thanks
I do not see same version into pom.xml of dev and master branches.
<mongodb-sync-4.version>4.2.3</mongodb-sync-4.version>
instead of
 <mongodb-sync-4.version>4.3.2</mongodb-sync-4.version>
Actually, we would like to create mongo time series with mongock and as far as I know we need 4.3.2 version of java driver.

**Comment by dieppa** [comment]
Sorry, it was a mistake, the version currently in use is **4.2.3**.

We'll release a new version next week or the week after(more likely next week) with the latest versions.
But you would need to upgrade to Mongock version 5. Here you have a [document](https://github.com/mongock/mongock-driver-mongodb/blob/develop/QUICK_UPGRADE_VERSION_5.md) in which we briefly explain how to upgrade. 

If you need anything, please let us know.

Cheers

**Comment by dieppa** [comment]
Hello @tleveque ,

we have release the version 5.0.20.RC. With the previous version you could use the latest version of MongoDB, however there were some stuff you needed to do, specially if you were using MongockTemplate.

Now we have fixed and you can use any version of MongoDB you want with no problem.


> Just a note. When testing mongodb-sync:4.3.3, for some reasons it was importing the version 4.1.1 of the bson and mongodb-core, we had to explicitly import these ones too. It seems that our systems was confused,  but in case you get an error about some method not found, it's worthy to do a `mvn dependency:tree` to double check 😉
